[Main]
Passthrough = false  ; Set to true to forward through all intercepted methods without any manipulation
OriginalMfDllName = m_.dll  ; Path to the original mf.dll, which should be named m_.dll and located in an accessible library loader search folder
PMPInitMode = UnprotectedProcessPMP  ; How to manipulate the creation of PMP sessions
; Modes:
; - UnprotectedProcessPMP: Modify PMP session creation flags to always start in an unprotected process. The session will still use PMP, but DRM capabilities and hangs will be absent.
; - ForceNonPMP: Force PMP sessions to be created as normal sessions instead (non-PMP). Might break applications that expect an IMFActivate interface or other key PMP features.
WatchConfigFile = false  ; If true, live changes to this config file will be detected and loaded, while the host application is running. If false, this config file is only loaded once, at application init.

[Debug]
AlertSessionCreation = false  ; if true, a message box will be shown each time we intercept a PMP session creation
